hostname: shopserver
samba_user: shopserver
samba_pass: shopserver
guest_ok_main: false
main_path: /srv/shopserver/shopserver
removable_base: /srv/shopserver/removable
images_path: /srv/shopserver/images
