hostname: shopserver
samba_user: shopserver
samba_pass: shopserver
guest_ok_main: false
main_path: /srv/shopserver/shopserver
removable_base: /srv/shopserver/removable
images_path: /srv/shopserver/images
data_user: shopserver
data_group: shopserver
data_uid: 1000
data_gid: 1000
smb1_share_name: shopserver-smb1
